server:
  port: 8091
  
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-1?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234